// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AuthenticateAgent(agentName: string, methodID: string): $CancellablePromise<$models.AgentTestResult> {
    return $Call.ByID(2194939229, agentName, methodID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function DiscoverAgentModes(agentName: string, cwd: string, force: boolean): $CancellablePromise<$models.AgentDescriptor> {
    return $Call.ByID(855155597, agentName, cwd, force).then(($result: any) => {
        return $$createType1($result);
    });
}

export function TestAgent(agentName: string): $CancellablePromise<$models.AgentTestResult> {
    return $Call.ByID(1141260718, agentName).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.AgentTestResult.createFrom;
const $$createType1 = $models.AgentDescriptor.createFrom;
