// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AgentConfig {
    "command": string;
    "args": string[];
    "env": { [_ in string]?: string };

    /** Creates a new AgentConfig instance. */
    constructor($$source: Partial<AgentConfig> = {}) {
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = [];
        }
        if (!("env" in $$source)) {
            this["env"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentConfig {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField1_0($$parsedSource["args"]);
        }
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField2_0($$parsedSource["env"]);
        }
        return new AgentConfig($$parsedSource as Partial<AgentConfig>);
    }
}

export class AgentDescriptor {
    "name": string;
    "command": string;
    "args": string[];
    "env": { [_ in string]?: string };
    "currentModeId": string;
    "modelOption"?: SessionConfigOption | null;
    "modes": SessionMode[];
    "modesDiscoveredAt": string;

    /** Creates a new AgentDescriptor instance. */
    constructor($$source: Partial<AgentDescriptor> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = [];
        }
        if (!("env" in $$source)) {
            this["env"] = {};
        }
        if (!("currentModeId" in $$source)) {
            this["currentModeId"] = "";
        }
        if (!("modes" in $$source)) {
            this["modes"] = [];
        }
        if (!("modesDiscoveredAt" in $$source)) {
            this["modesDiscoveredAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentDescriptor {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField2_0($$parsedSource["args"]);
        }
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField3_0($$parsedSource["env"]);
        }
        if ("modelOption" in $$parsedSource) {
            $$parsedSource["modelOption"] = $$createField5_0($$parsedSource["modelOption"]);
        }
        if ("modes" in $$parsedSource) {
            $$parsedSource["modes"] = $$createField6_0($$parsedSource["modes"]);
        }
        return new AgentDescriptor($$parsedSource as Partial<AgentDescriptor>);
    }
}

export class AgentTestResult {
    "agentName": string;
    "agentTitle": string;
    "agentVersion": string;
    "protocolVersion": number;
    "promptCapabilities": PromptCapabilities;
    "loadSession": boolean;
    "authMethods": AuthMethod[];

    /** Creates a new AgentTestResult instance. */
    constructor($$source: Partial<AgentTestResult> = {}) {
        if (!("agentName" in $$source)) {
            this["agentName"] = "";
        }
        if (!("agentTitle" in $$source)) {
            this["agentTitle"] = "";
        }
        if (!("agentVersion" in $$source)) {
            this["agentVersion"] = "";
        }
        if (!("protocolVersion" in $$source)) {
            this["protocolVersion"] = 0;
        }
        if (!("promptCapabilities" in $$source)) {
            this["promptCapabilities"] = (new PromptCapabilities());
        }
        if (!("loadSession" in $$source)) {
            this["loadSession"] = false;
        }
        if (!("authMethods" in $$source)) {
            this["authMethods"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentTestResult instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentTestResult {
        const $$createField4_0 = $$createType6;
        const $$createField6_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("promptCapabilities" in $$parsedSource) {
            $$parsedSource["promptCapabilities"] = $$createField4_0($$parsedSource["promptCapabilities"]);
        }
        if ("authMethods" in $$parsedSource) {
            $$parsedSource["authMethods"] = $$createField6_0($$parsedSource["authMethods"]);
        }
        return new AgentTestResult($$parsedSource as Partial<AgentTestResult>);
    }
}

export class AuthMethod {
    "id": string;
    "name": string;
    "description": string;

    /** Creates a new AuthMethod instance. */
    constructor($$source: Partial<AuthMethod> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthMethod instance from a string or object.
     */
    static createFrom($$source: any = {}): AuthMethod {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuthMethod($$parsedSource as Partial<AuthMethod>);
    }
}

export class ChiselSettings {
    "agents": { [_ in string]?: AgentConfig };

    /** Creates a new ChiselSettings instance. */
    constructor($$source: Partial<ChiselSettings> = {}) {
        if (!("agents" in $$source)) {
            this["agents"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChiselSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): ChiselSettings {
        const $$createField0_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("agents" in $$parsedSource) {
            $$parsedSource["agents"] = $$createField0_0($$parsedSource["agents"]);
        }
        return new ChiselSettings($$parsedSource as Partial<ChiselSettings>);
    }
}

export class CreateSessionRequest {
    "agentName": string;
    "cwd": string;
    "titleHint": string;

    /** Creates a new CreateSessionRequest instance. */
    constructor($$source: Partial<CreateSessionRequest> = {}) {
        if (!("agentName" in $$source)) {
            this["agentName"] = "";
        }
        if (!("cwd" in $$source)) {
            this["cwd"] = "";
        }
        if (!("titleHint" in $$source)) {
            this["titleHint"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateSessionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateSessionRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateSessionRequest($$parsedSource as Partial<CreateSessionRequest>);
    }
}

export class PermissionOption {
    "id": string;
    "name": string;
    "kind": string;
    "description": string;

    /** Creates a new PermissionOption instance. */
    constructor($$source: Partial<PermissionOption> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PermissionOption instance from a string or object.
     */
    static createFrom($$source: any = {}): PermissionOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PermissionOption($$parsedSource as Partial<PermissionOption>);
    }
}

export class PermissionRequest {
    "requestId": string;
    "sessionId": string;
    "toolCallId": string;
    "title": string;
    "description": string;
    "options": PermissionOption[];
    "createdAt": string;

    /** Creates a new PermissionRequest instance. */
    constructor($$source: Partial<PermissionRequest> = {}) {
        if (!("requestId" in $$source)) {
            this["requestId"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("toolCallId" in $$source)) {
            this["toolCallId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("options" in $$source)) {
            this["options"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PermissionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): PermissionRequest {
        const $$createField5_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField5_0($$parsedSource["options"]);
        }
        return new PermissionRequest($$parsedSource as Partial<PermissionRequest>);
    }
}

export class PlanEntry {
    "content": string;
    "status": string;
    "priority": string;

    /** Creates a new PlanEntry instance. */
    constructor($$source: Partial<PlanEntry> = {}) {
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlanEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): PlanEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlanEntry($$parsedSource as Partial<PlanEntry>);
    }
}

export class PromptCapabilities {
    "image": boolean;
    "audio": boolean;
    "embeddedContext": boolean;

    /** Creates a new PromptCapabilities instance. */
    constructor($$source: Partial<PromptCapabilities> = {}) {
        if (!("image" in $$source)) {
            this["image"] = false;
        }
        if (!("audio" in $$source)) {
            this["audio"] = false;
        }
        if (!("embeddedContext" in $$source)) {
            this["embeddedContext"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptCapabilities instance from a string or object.
     */
    static createFrom($$source: any = {}): PromptCapabilities {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PromptCapabilities($$parsedSource as Partial<PromptCapabilities>);
    }
}

export class SessionConfigOption {
    "id": string;
    "name": string;
    "description": string;
    "category": string;
    "type": string;
    "currentValue": string;
    "values": SessionConfigValue[];

    /** Creates a new SessionConfigOption instance. */
    constructor($$source: Partial<SessionConfigOption> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("currentValue" in $$source)) {
            this["currentValue"] = "";
        }
        if (!("values" in $$source)) {
            this["values"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionConfigOption instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionConfigOption {
        const $$createField6_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("values" in $$parsedSource) {
            $$parsedSource["values"] = $$createField6_0($$parsedSource["values"]);
        }
        return new SessionConfigOption($$parsedSource as Partial<SessionConfigOption>);
    }
}

export class SessionConfigValue {
    "value": string;
    "name": string;
    "description": string;
    "groupId": string;
    "groupName": string;

    /** Creates a new SessionConfigValue instance. */
    constructor($$source: Partial<SessionConfigValue> = {}) {
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("groupId" in $$source)) {
            this["groupId"] = "";
        }
        if (!("groupName" in $$source)) {
            this["groupName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionConfigValue instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionConfigValue {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionConfigValue($$parsedSource as Partial<SessionConfigValue>);
    }
}

export class SessionEvent {
    "sessionId": string;
    "kind": string;
    "timestamp": string;
    "messageRole"?: string;
    "text"?: string;
    "thought"?: string;
    "toolCall"?: ToolCallRecord | null;
    "permission"?: PermissionRequest | null;
    "stopReason"?: string;
    "title"?: string;
    "configOptions"?: SessionConfigOption[];
    "currentModeId"?: string;
    "modes"?: SessionMode[];
    "plan"?: PlanEntry[];
    "error"?: string;
    "method"?: string;
    "raw"?: string;

    /** Creates a new SessionEvent instance. */
    constructor($$source: Partial<SessionEvent> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionEvent {
        const $$createField6_0 = $$createType16;
        const $$createField7_0 = $$createType18;
        const $$createField10_0 = $$createType19;
        const $$createField12_0 = $$createType5;
        const $$createField13_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("toolCall" in $$parsedSource) {
            $$parsedSource["toolCall"] = $$createField6_0($$parsedSource["toolCall"]);
        }
        if ("permission" in $$parsedSource) {
            $$parsedSource["permission"] = $$createField7_0($$parsedSource["permission"]);
        }
        if ("configOptions" in $$parsedSource) {
            $$parsedSource["configOptions"] = $$createField10_0($$parsedSource["configOptions"]);
        }
        if ("modes" in $$parsedSource) {
            $$parsedSource["modes"] = $$createField12_0($$parsedSource["modes"]);
        }
        if ("plan" in $$parsedSource) {
            $$parsedSource["plan"] = $$createField13_0($$parsedSource["plan"]);
        }
        return new SessionEvent($$parsedSource as Partial<SessionEvent>);
    }
}

export class SessionLoadResult {
    "session": SessionSummary;
    "configOptions": SessionConfigOption[];
    "currentModeId": string;
    "modes": SessionMode[];
    "promptCapabilities": PromptCapabilities;

    /** Creates a new SessionLoadResult instance. */
    constructor($$source: Partial<SessionLoadResult> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new SessionSummary());
        }
        if (!("configOptions" in $$source)) {
            this["configOptions"] = [];
        }
        if (!("currentModeId" in $$source)) {
            this["currentModeId"] = "";
        }
        if (!("modes" in $$source)) {
            this["modes"] = [];
        }
        if (!("promptCapabilities" in $$source)) {
            this["promptCapabilities"] = (new PromptCapabilities());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionLoadResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionLoadResult {
        const $$createField0_0 = $$createType22;
        const $$createField1_0 = $$createType19;
        const $$createField3_0 = $$createType5;
        const $$createField4_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        if ("configOptions" in $$parsedSource) {
            $$parsedSource["configOptions"] = $$createField1_0($$parsedSource["configOptions"]);
        }
        if ("modes" in $$parsedSource) {
            $$parsedSource["modes"] = $$createField3_0($$parsedSource["modes"]);
        }
        if ("promptCapabilities" in $$parsedSource) {
            $$parsedSource["promptCapabilities"] = $$createField4_0($$parsedSource["promptCapabilities"]);
        }
        return new SessionLoadResult($$parsedSource as Partial<SessionLoadResult>);
    }
}

export class SessionMode {
    "id": string;
    "name": string;
    "description": string;

    /** Creates a new SessionMode instance. */
    constructor($$source: Partial<SessionMode> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionMode instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionMode {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionMode($$parsedSource as Partial<SessionMode>);
    }
}

export class SessionSummary {
    "sessionId": string;
    "agentName": string;
    "cwd": string;
    "title": string;
    "createdAt": string;
    "updatedAt": string;
    "lastOpenedAt": string;

    /** Creates a new SessionSummary instance. */
    constructor($$source: Partial<SessionSummary> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("agentName" in $$source)) {
            this["agentName"] = "";
        }
        if (!("cwd" in $$source)) {
            this["cwd"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }
        if (!("lastOpenedAt" in $$source)) {
            this["lastOpenedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionSummary($$parsedSource as Partial<SessionSummary>);
    }
}

export class ToolCallContent {
    "type": string;
    "text": string;
    "path": string;
    "uri": string;
    "mimeType": string;
    "terminalId": string;
    "output": string;
    "exitCode": number;
    "exitCodeSet": boolean;
    "isTruncated": boolean;
    "description": string;

    /** Creates a new ToolCallContent instance. */
    constructor($$source: Partial<ToolCallContent> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("uri" in $$source)) {
            this["uri"] = "";
        }
        if (!("mimeType" in $$source)) {
            this["mimeType"] = "";
        }
        if (!("terminalId" in $$source)) {
            this["terminalId"] = "";
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }
        if (!("exitCode" in $$source)) {
            this["exitCode"] = 0;
        }
        if (!("exitCodeSet" in $$source)) {
            this["exitCodeSet"] = false;
        }
        if (!("isTruncated" in $$source)) {
            this["isTruncated"] = false;
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolCallContent instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolCallContent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolCallContent($$parsedSource as Partial<ToolCallContent>);
    }
}

export class ToolCallRecord {
    "toolCallId": string;
    "title": string;
    "kind": string;
    "status": string;
    "content": ToolCallContent[];

    /** Creates a new ToolCallRecord instance. */
    constructor($$source: Partial<ToolCallRecord> = {}) {
        if (!("toolCallId" in $$source)) {
            this["toolCallId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolCallRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolCallRecord {
        const $$createField4_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("content" in $$parsedSource) {
            $$parsedSource["content"] = $$createField4_0($$parsedSource["content"]);
        }
        return new ToolCallRecord($$parsedSource as Partial<ToolCallRecord>);
    }
}

export class WorkspaceSummary {
    "path": string;
    "lastOpenedAt": string;

    /** Creates a new WorkspaceSummary instance. */
    constructor($$source: Partial<WorkspaceSummary> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("lastOpenedAt" in $$source)) {
            this["lastOpenedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceSummary($$parsedSource as Partial<WorkspaceSummary>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = SessionConfigOption.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = SessionMode.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = PromptCapabilities.createFrom;
const $$createType7 = AuthMethod.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = AgentConfig.createFrom;
const $$createType10 = $Create.Map($Create.Any, $$createType9);
const $$createType11 = PermissionOption.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = SessionConfigValue.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = ToolCallRecord.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = PermissionRequest.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = $Create.Array($$createType2);
const $$createType20 = PlanEntry.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = SessionSummary.createFrom;
const $$createType23 = ToolCallContent.createFrom;
const $$createType24 = $Create.Array($$createType23);
