// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ListPendingPermissions(): $CancellablePromise<$models.PermissionRequest[]> {
    return $Call.ByID(4026726603).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ResolvePermission(requestID: string, selectedOptionID: string, cancelled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1404874673, requestID, selectedOptionID, cancelled);
}

// Private type creation functions
const $$createType0 = $models.PermissionRequest.createFrom;
const $$createType1 = $Create.Array($$createType0);
