// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelPrompt(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1772783565, sessionID);
}

export function CreateSession(request: $models.CreateSessionRequest): $CancellablePromise<$models.SessionLoadResult> {
    return $Call.ByID(4095665835, request).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ForgetSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2380950996, sessionID);
}

export function ListRecentWorkspaces(): $CancellablePromise<$models.WorkspaceSummary[]> {
    return $Call.ByID(4109430228).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListSessions(): $CancellablePromise<$models.SessionSummary[]> {
    return $Call.ByID(1911720108).then(($result: any) => {
        return $$createType4($result);
    });
}

export function LoadSession(sessionID: string): $CancellablePromise<$models.SessionLoadResult> {
    return $Call.ByID(2016859943, sessionID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function PickWorkspace(initialDir: string): $CancellablePromise<string> {
    return $Call.ByID(819970137, initialDir);
}

export function SendPrompt(sessionID: string, prompt: string): $CancellablePromise<void> {
    return $Call.ByID(340378745, sessionID, prompt);
}

export function SetConfigOption(sessionID: string, optionID: string, value: string): $CancellablePromise<$models.SessionLoadResult> {
    return $Call.ByID(2340331276, sessionID, optionID, value).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SetMode(sessionID: string, modeID: string): $CancellablePromise<$models.SessionLoadResult> {
    return $Call.ByID(1944019208, sessionID, modeID).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.SessionLoadResult.createFrom;
const $$createType1 = $models.WorkspaceSummary.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.SessionSummary.createFrom;
const $$createType4 = $Create.Array($$createType3);
