// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetSettings(): $CancellablePromise<$models.ChiselSettings> {
    return $Call.ByID(3034808949).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListAgents(): $CancellablePromise<$models.AgentDescriptor[]> {
    return $Call.ByID(1247677994).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SaveSettings(settings: $models.ChiselSettings): $CancellablePromise<void> {
    return $Call.ByID(2662658340, settings);
}

// Private type creation functions
const $$createType0 = $models.ChiselSettings.createFrom;
const $$createType1 = $models.AgentDescriptor.createFrom;
const $$createType2 = $Create.Array($$createType1);
